Path Position:
  - [Orange, Red, Blue]
  - [Brown, Purple, Yellow]
  
Path Edges:
  - [Orange, Red]
  - [Orange, Brown]
  - [Red, Blue]
  - [Red, Purple]
  - [Brown, Purple]
  - [Purple, Yellow]
  - [Blue, Yellow]

Categories Positions:
  1st floor: 
    Eletrônica: [Orange, Red]
    Cálculo: [Red, Blue]
    Física: [Brown, Purple]
    Química: [Purple, Yellow]
  
  2nd floor: 
    Ficção: [Orange, Red]
    Circuitos: [Red, Blue]
    Biologia: [Brown, Purple]
    Literatura: [Purple, Yellow]

Scout Path: [Orange, Red, Blue, Yellow, Purple, Brown]

